/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ReceitasRouteImport } from './routes/receitas'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as OndeComprarRouteImport } from './routes/onde-comprar'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceitasSlugRouteImport } from './routes/receitas.$slug'
import { Route as ProdutosSlugRouteImport } from './routes/produtos.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitasRoute = ReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const OndeComprarRoute = OndeComprarRouteImport.update({
  id: '/onde-comprar',
  path: '/onde-comprar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitasSlugRoute = ReceitasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ReceitasRoute,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProdutosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/onde-comprar': typeof OndeComprarRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/receitas': typeof ReceitasRouteWithChildren
  '/sobre': typeof SobreRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/receitas/$slug': typeof ReceitasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/onde-comprar': typeof OndeComprarRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/receitas': typeof ReceitasRouteWithChildren
  '/sobre': typeof SobreRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/receitas/$slug': typeof ReceitasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/onde-comprar': typeof OndeComprarRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/receitas': typeof ReceitasRouteWithChildren
  '/sobre': typeof SobreRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/receitas/$slug': typeof ReceitasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contactos'
    | '/onde-comprar'
    | '/produtos'
    | '/receitas'
    | '/sobre'
    | '/produtos/$slug'
    | '/receitas/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contactos'
    | '/onde-comprar'
    | '/produtos'
    | '/receitas'
    | '/sobre'
    | '/produtos/$slug'
    | '/receitas/$slug'
  id:
    | '__root__'
    | '/'
    | '/contactos'
    | '/onde-comprar'
    | '/produtos'
    | '/receitas'
    | '/sobre'
    | '/produtos/$slug'
    | '/receitas/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactosRoute: typeof ContactosRoute
  OndeComprarRoute: typeof OndeComprarRoute
  ProdutosRoute: typeof ProdutosRouteWithChildren
  ReceitasRoute: typeof ReceitasRouteWithChildren
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receitas': {
      id: '/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof ReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onde-comprar': {
      id: '/onde-comprar'
      path: '/onde-comprar'
      fullPath: '/onde-comprar'
      preLoaderRoute: typeof OndeComprarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receitas/$slug': {
      id: '/receitas/$slug'
      path: '/$slug'
      fullPath: '/receitas/$slug'
      preLoaderRoute: typeof ReceitasSlugRouteImport
      parentRoute: typeof ReceitasRoute
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof ProdutosRoute
    }
  }
}

interface ProdutosRouteChildren {
  ProdutosSlugRoute: typeof ProdutosSlugRoute
}

const ProdutosRouteChildren: ProdutosRouteChildren = {
  ProdutosSlugRoute: ProdutosSlugRoute,
}

const ProdutosRouteWithChildren = ProdutosRoute._addFileChildren(
  ProdutosRouteChildren,
)

interface ReceitasRouteChildren {
  ReceitasSlugRoute: typeof ReceitasSlugRoute
}

const ReceitasRouteChildren: ReceitasRouteChildren = {
  ReceitasSlugRoute: ReceitasSlugRoute,
}

const ReceitasRouteWithChildren = ReceitasRoute._addFileChildren(
  ReceitasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactosRoute: ContactosRoute,
  OndeComprarRoute: OndeComprarRoute,
  ProdutosRoute: ProdutosRouteWithChildren,
  ReceitasRoute: ReceitasRouteWithChildren,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
